import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://www.quhealthy.org';

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/es/*',
          '/en/*',
          '/sitemap.xml',
        ],
        disallow: [
          '/admin/*',
          '/*/admin/*',
          '/patient/*',
          '/*/patient/*',
          '/provider/*',
          '/*/provider/*',
          '/foundation/dashboard/*',
          '/*/foundation/dashboard/*',
          '/*/foundation/settings/*',
          '/*/foundation/beneficiaries/*',
          '/*/foundation/campaigns/*',
          '/*/foundation/programs/*',
          '/*/foundation/subsidies/*',
          '/*/foundation/team/*',
          '/supplier/dashboard/*',
          '/*/supplier/dashboard/*',
          '/*/supplier/inventory/*',
          '/*/supplier/orders/*',
          '/*/supplier/products/*',
          '/*/supplier/quotes/*',
          '/*/supplier/rentals/*',
          '/*/supplier/cold-chain/*',
          '/onboarding/*',
          '/*/onboarding/*',
          '/login',
          '/*/login',
          '/register',
          '/*/register',
          '/forgot-password',
          '/*/forgot-password',
          '/reset-password',
          '/*/reset-password',
          '/verify-email',
          '/*/verify-email',
          '/verify-phone',
          '/*/verify-phone',
          '/staff/activate',
          '/*/staff/activate',
          '/checkout',
          '/*/checkout',
          '/budget/*',
          '/*/budget/*',
          '/api/*',
          '/*?*clear_session=*',
          '/*?*token=*',
        ],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
